# Generated by Django 4.2.4 on 2024-03-26 02:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[("Pending", "Pending"), ("Complete", "Complete")],
                default="Pending",
                max_length=50,
            ),
        ),
    ]
