# Generated by Django 4.2.4 on 2024-03-26 08:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0005_productimage"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ProductImage",
        ),
    ]
