# Generated by Django 4.2.4 on 2024-03-28 08:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0006_delete_productimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="storemodel",
            name="background_image",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="media/",
                verbose_name="background iamge",
            ),
        ),
        migrations.AddField(
            model_name="storemodel",
            name="logo1",
            field=models.FileField(
                blank=True, null=True, upload_to="media/", verbose_name="logo1"
            ),
        ),
        migrations.AddField(
            model_name="storemodel",
            name="logo2",
            field=models.FileField(
                blank=True, null=True, upload_to="media/", verbose_name="logo2"
            ),
        ),
    ]
