# Generated by Django 4.2.4 on 2024-03-28 09:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0007_storemodel_background_image_storemodel_logo1_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="store",
        ),
    ]
